### ISSUE TITLE
Incluir o diretório .metadata no gitignore.

### ISSUE THREAD

**Issue by iagosaito** [feernandoaleencar/gerenciador_de_sinuca#5]
**Motivação**

Não é preciso incluir o diretório .metadata no repositório, inclusive o recomendado é que esse arquivo seja ignorado. 

**Possíveis Riscos**
Nenhum

**Sugestões de como resolver**
Existem alguns sites que possuem um catálogo desses diretórios e outras aplicações já formatadas para o gitignore. O próprio Github possui um: https://github.com/github/gitignore.

Outro exemplo é o: https://www.toptal.com/developers/gitignore

**Comment by feernandoaleencar** [comment]
Muito Obrigado pelo feedback. 

Inserir no gitignore e deletei o diretório aqui do repositório.
